# all information what needed to be hidden put in to docker-compose.override.yml
version: "3"

services:
  admin:
    image: nginx:latest
    volumes:
      - ./:/code:rw
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always
    # set env property ( VIRTUAL_HOST ) in docker-compose.override.yml
  php:
    build: ./docker/php
    volumes:
      - ./:/code:rw
    working_dir: /code
    links:
      - db
    restart: always
  db:
    image: mysql:latest
    volumes:
      - ./docker/database:/var/lib/mysql:rw
      - ./docker/db.cnf:/etc/mysql/conf.d/use_native_password_auth_method.cnf
    environment:
      - MYSQL_DATABASE=spn # SET MYSQL_ROOT_PASSWORD in docker-compose.override.yml
    restart: always
networks:
  default:
    external:
      name: nginx-proxy